global:
  scrape_interval: 15s
scrape_configs:
- job_name: 'containers'
  docker_sd_configs:
  - host: unix:///run/docker.sock
  relabel_configs:
  - source_labels: ['__meta_docker_container_name']
    regex: '/testcase-(.*)'
    target_label: 'app'
    action: replace
  - source_labels: ['__meta_docker_container_name']
    regex: '.*(prometheus)'
    target_label: 'app'
    action: replace
rule_files:
  - /etc/prometheus/alerts.yml