global:
  scrape_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
      # - prometheus:9090
      - app:3001
  - job_name: 'docker_containers'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
rule_files:
  - /etc/prometheus/alerts.yml